version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.11"
  jobs:
    pre_build:
      - pip install poetry
      - poetry config virtualenvs.create false
      - poetry install --only docs

sphinx:
  configuration: docs/source/conf.py
